### ISSUE TITLE
Not Building under windows.

### ISSUE THREAD

**Issue by sourcepirate** [wiesel78/wiesels-mousejs#2]
When I Try to Build this module for window. i am getting an error like this.

TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [C:\Users\Synclio Test\node_modules\wiesels-mousejs\node_modul
es\ref\build\binding.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046
:12)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "node" "c:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Synclio Test\node_modules\wiesels-mousejs\node_modules\ref

gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok

> ref@0.3.5 install C:\Users\Synclio Test\node_modules\wiesels-mousejs\node_modu
> les\ref-struct\node_modules\ref
> node-gyp rebuild

C:\Users\Synclio Test\node_modules\wiesels-mousejs\node_modules\ref-struct\node_
modules\ref>node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\..\
..\node_modules\node-gyp\bin\node-gyp.js" rebuild
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(29
6,5): warning MSB8003: Could not find VCInstallDir variable from the registry.
 TargetFrameworkVersion or PlatformToolset may be set to an invalid version num
ber. [C:\Users\Test\node_modules\wiesels-mousejs\node_modules\ref-struc
t\node_modules\ref\build\binding.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Microsoft.CppBuild.targets(29
7,5): warning MSB8003: Could not find WindowsSDKDir variable from the registry.
  TargetFrameworkVersion or PlatformToolset may be set to an invalid version nu
mber. [C:\Users\Test\node_modules\wiesels-mousejs\node_modules\ref-stru
ct\node_modules\ref\build\binding.vcxproj]
TRACKER : error TRK0005: Failed to locate: "CL.exe". The system cannot find the
 file specified. [C:\Users\Test\node_modules\wiesels-mousejs\node_modul
es\ref-struct\node_modules\ref\build\binding.vcxproj]

gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1046
:12)
gyp ERR! System Windows_NT 6.1.7600
gyp ERR! command "node" "c:\Program Files\nodejs\node_modules\npm\node_modu
les\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Test\node_modules\wiesels-mousejs\node_modules\ref
-struct\node_modules\ref
gyp ERR! node -v v0.11.13
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok

> ffi@1.2.7 install C:\Users\Test\node_modules\wiesels-mousejs\node_modu
> les\ffi
> node-gyp rebuild

**Comment by wiesel78** [comment]
Is fixed now. 
I replace node-ffi with edge.js on windows.
Ignore node-ffi build errors!
